### PR TITLE
Revert "SNOW-1730434 curl upgrade 8.10.1 (#758)"

### PR DESCRIPTION
**Pull request by sfc-gh-jszczerbinski**
This reverts commit dd76ce4ea71b5e785b5206ad6e116bb873b19270.

Curl update was incorrectly performed, not all files from old curl version were deleted. This caused conflicts between files in the repo on case-insensitive filesystems. Following files are remains of the old curl version and cause collision: 
- deps/curl/CMake/FindCARES.cmake
- deps/curl/CMake/FindLibPSL.cmake
- deps/curl/CMake/FindLibSSH2.cmake 
- deps/curl/CMake/FindQUICHE.cmake

image

### CODE REVIEW

**Comment by sfc-gh-ext-simba-hx** [comment]
Can we get the 4 files removed instead of entirely reverting the curl update?
The current approach (overwrite instead of entirely deleting old one) is for #1051

**Comment by sfc-gh-jszczerbinski** [comment]
I disagree. It blocks all commits from branches based on master (due to collisions secret detection fails).

**Review by sfc-gh-mkubik — APPROVED** [review]

**Review by sfc-gh-dheyman-1 — APPROVED** [review]

**Comment by sfc-gh-jszczerbinski** [comment]
@sfc-gh-ext-simba-hx Can you make you redo the PR where you remove all the files from the old curl version.

**Comment by sfc-gh-jszczerbinski** [comment]
Seems like we want to have this in the next release. New PR already in progress: https://github.com/snowflakedb/libsnowflakeclient/pull/761

**Pull request merged**
