### PR TITLE
bump up libsnowflakeclient version to 1.0.5

### PR DESCRIPTION
**Pull request by sfc-gh-ext-simba-hx**
**New Features and Improvements**
- N/A

**Behavior Changes**
- N/A

**Bug Fixes**
- removed banned function calls https://github.com/snowflakedb/libsnowflakeclient/pull/602

**Test Fix/ Internal Changes**
- Fix the test failures on Linux https://github.com/snowflakedb/libsnowflakeclient/pull/626

### CODE REVIEW

**Comment by sfc-gh-dprzybysz** [comment]
It would be great to include in this release also https://github.com/snowflakedb/libsnowflakeclient/pull/647

**Comment by sfc-gh-ext-simba-hx** [comment]
@sfc-gh-dprzybysz 
Please see my comment here https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/643#issuecomment-1832917204
Since it's internal improvement and not fixing any customer issue, I think it's better to hold it back before we can confirm through e2e test that no functionality change with it.

**Review by sfc-gh-kdama — COMMENTED** [review]
LGTM 👍

**Comment by sfc-gh-ext-simba-hx** [comment]
Discussed with @sfc-gh-igarish
Since https://github.com/snowflakedb/libsnowflakeclient/pull/647 is internal improvement no customer waiting for it, also we are facing issue during the test, push it to Jan release.

**Pull request merged**
