### PR TITLE
Upgrade curl to 7.68.0

### PR DESCRIPTION
**Pull request by SimbaGithub**
Merged all custom changes in 7.66.0 to 7.68.0 and changed curl version in build scripts.

### CODE REVIEW

**Comment by snowstakeda** [comment]
will look into this.

**Comment by SimbaGithub** [comment]
Thanks!

**Comment by snowstakeda** [comment]
@SimbaGithub I think the problem is all source codes have CRLF instead of LF.

**Comment by snowstakeda** [comment]
Trying to fix it now

**Comment by SimbaGithub** [comment]
Thanks for your help @snowstakeda ! I can fix that.

**Comment by snowstakeda** [comment]
Fixing this too:
```
  CCLD     libcurlu.la
libtool: warning: library '/home/debugger/libsnowflakeclient/scripts/../deps-build/linux/Debug/uuid/lib/libuuid.la' was moved.
  RUN      checksrc
./setopt.c:1847:11: error: Contains TAB character (TABS)
     break;
           ^
./setopt.c:1847:11: warning: Trailing whitespace (TRAILINGSPACE)
     break;
           ^
./url.c:1617:50: error: Contains TAB character (TABS)
     data->set.proxy_ssl.primary.sf_ocsp_failopen;
                                                  ^
./url.c:1617:50: warning: Trailing whitespace (TRAILINGSPACE)
     data->set.proxy_ssl.primary.sf_ocsp_failopen;
                                                  ^
checksrc: 0 errors and 4 warnings
checksrc: 0 errors and 5 warnings suppressed
make[2]: *** [checksrc] Error 5
```

**Comment by snowstakeda** [comment]
@SimbaGithub , let me push the change here.

**Comment by snowstakeda** [comment]
Nevermind. I'll push the changes to other branch for test. The local test passed.

**Comment by SimbaGithub** [comment]
Thanks!

**Comment by snowstakeda** [comment]
Moving this change to #192

**Pull request closed without merging**
