### PR TITLE
Using time_t instead of int 32 to avoid overflow SNOW-81888

### PR DESCRIPTION
**Pull request by sfc-gh-smirzaei**
Description
@sfc-gh-kwagner this is change that I did for SNOW-81888 locally quite a while ago (in branch I created for stored proc) but fell through crack to be checked into the main repo

### CODE REVIEW

**Comment by sfc-gh-smirzaei** [comment]
I have some issues with running the tests locally. Do you have any sense why test_simple_put_uploadfail may be failing?!

**Comment by sfc-gh-kwagner** [comment]
> I have some issues with running the tests locally. Do you have any sense why test_simple_put_uploadfail may be failing?!

@sfc-gh-smirzaei I imagine that your environment isn't setup for put tests. @sfc-gh-vreddy is there anything that needs to be done to setup put tests on libsnowflakeclient?

**Comment by sfc-gh-vreddy** [comment]
@sfc-gh-smirzaei @sfc-gh-kwagner 
```
SNOWFLAKE_TEST_ACCOUNT=aztestaccount
SNOWFLAKE_TEST_USER=vreddy
SNOWFLAKE_TEST_PASSWORD=password
SNOWFLAKE_TEST_DATABASE=TESTDB
SNOWFLAKE_TEST_SCHEMA=AZUREPUTGET
SNOWFLAKE_TEST_WAREHOUSE=VREDDY
SNOWFLAKE_TEST_HOST=aztestaccount.east-us-2.azure.snowflakecomputing.com
SNOWFLAKE_TEST_PORT=443
SNOWFLAKE_TEST_ROLE=SYSADMIN
SNOWFLAKE_TEST_PROTOCOL=https
SNOWFLAKE_CLOUD_ENV=AZURE
CLOUD_PROVIDER=AZURE
SNOWFLAKE_TEST_CA_BUNDLE_FILE=/etc/pki/tls/cacert.pem
```
your testing environment should have these set. 
SNOWFLAKE_CLOUD_ENV and CLOUD_PROVIDER should be set according to the provider
possible values: AZURE , AWS

**Comment by sfc-gh-vreddy** [comment]
@sfc-gh-smirzaei put/get tests do not run in linux but are run on windows/mac
 There is a issue in docker that makes the tests fail on jenkins.
If you want to enable in local dev vm you can add that to 
tests/CMakeLists.txt
```
if (APPLE OR WIN32)
    set(TESTS_CXX ${TESTS_CXX} ${TESTS_PUTGET})
endif ()
if (UNIX)
    set(TESTS_CXX ${TESTS_CXX} ${TESTS_PUTGET})      ------------>This is the addition.
    find_library(CMOCKA_LIB libcmocka.a PATHS ../deps-build/${PLATFORM}/cmocka/lib/ REQUIRED)
    find_library(AZURE_STORAGE_LITE_LIB libazure-storage-lite.a PATHS ../deps-build/${PLATFORM}/azure/lib/ REQUIRED)
    find_file(VALGRIND_SUPPRESSION valgrind_suppressions.txt utils)
endif ()
```

**Pull request merged**
