### PR TITLE
Simba changes for PUT/GET on GCP and bulk parameter array binding

### PR DESCRIPTION
**Pull request by SimbaGithub**
1. Support PUT/GET on GCP for ODBC Driver
2. Support Bulk parameter array binding for ODBC Driver

### CODE REVIEW

**Comment by sfc-gh-stakeda** [comment]
Got the compiler error on Mac 10.12:
```
 10%] Building CXX object CMakeFiles/snowflakeclient.dir/cpp/SnowflakeGCSClient.cpp.o
/usr/bin/clang++  -DLOG_USE_COLOR -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/oob/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/curl/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/openssl/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/zlib/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/aws/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/azure/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/deps-build/darwin/Debug/cmocka/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/include> -I<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/lib>  -std=c++11 -std=gnu++11 -fPIC -Werror  -g -arch x86_64 -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -o CMakeFiles/snowflakeclient.dir/cpp/SnowflakeGCSClient.cpp.o -c <https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.cpp>
In file included from <https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.cpp>:5:
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.hpp>:46:31: error: 'upload' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  RemoteStorageRequestOutcome upload(FileMetadata *fileMetadata,
                              ^
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/IStorageClient.hpp>:34:39: note: overridden virtual function is here
  virtual RemoteStorageRequestOutcome upload(FileMetadata *fileMetadata,
                                      ^
In file included from <https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.cpp>:5:
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.hpp>:49:31: error: 'download' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  RemoteStorageRequestOutcome download(FileMetadata *fileMetadata,
                              ^
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/IStorageClient.hpp>:25:39: note: overridden virtual function is here
  virtual RemoteStorageRequestOutcome download(FileMetadata * fileMetadata,
                                      ^
In file included from <https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.cpp>:5:
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/SnowflakeGCSClient.hpp>:52:31: error: 'GetRemoteFileMetadata' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  RemoteStorageRequestOutcome GetRemoteFileMetadata(
                              ^
<https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/ws/cpp/IStorageClient.hpp>:40:39: note: overridden virtual function is here
  virtual RemoteStorageRequestOutcome GetRemoteFileMetadata(
                                      ^
3 errors generated.
make[2]: *** [CMakeFiles/snowflakeclient.dir/cpp/SnowflakeGCSClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/snowflakeclient.dir/all] Error 2
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
[description-setter] Description set:
```

**Comment by sfc-gh-stakeda** [comment]
@rvishureddy, here is the list of libSnowflakeClient Jenkins jobs:
- https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/
- https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/
- https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Release/
- https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Release-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Release/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Release-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Debug/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Debug-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Release/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Release-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Debug/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Debug-Test/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Release/
- https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Release-Test/

As this PR is #198, look into the jobs including `origin/pr/198/merge`.

In my review, looks good except https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug-Test/358/console

Please confirm.

**Comment by sfc-gh-stakeda** [comment]
@SimbaGithub and @rvishureddy do we have a test case? If no, can you add one?

**Comment by SimbaGithub** [comment]
> @rvishureddy, here is the list of libSnowflakeClient Jenkins jobs:
> 
> * https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/
> * https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Debug/
> * https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Release/
> * https://localhost:8080/job/LibSnowflakeClient-Mac-Universal-Release-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Release/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Release-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Debug/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Debug-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Release/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win32-VS14-Release-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Debug/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Debug-Test/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Release/
> * https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Win64-VS14-Release-Test/
> 
> As this PR is #198, look into the jobs including `origin/pr/198/merge`.
> 
> In my review, looks good except https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug-Test/358/console
> 
> Please confirm.

I can't access https://jenkins.int.snowflakecomputing.com/view/SFTestClient/job/LibSnowflakeClient-Linux-Debug-Test/358/console, got 403 Forbidden.

**Comment by SimbaGithub** [comment]
> @SimbaGithub and @rvishureddy do we have a test case? If no, can you add one?

The added feature is used for ODBC driver. I could add test case there.

**Comment by rvishureddy** [comment]
@SimbaGithub Add a test case for GCS put/get and verify file. A reference implementation is available in test_simple_put.cpp

**Comment by rvishureddy** [comment]
@SimbaGithub JDBC GCS supports wild char upload. 
`put file:///home/test/test_file*.csv`
uploads file matching the pattern. Does the current implementation support this?

**Comment by sfc-gh-stakeda** [comment]
@SimbaGithub , sorry those Jenkins links are internal CI. We watch the build and test there and let you know.
@rvishureddy we need to enable the tests for all cloud providers. Can you do it soon?

**Comment by SimbaGithub** [comment]
> @SimbaGithub JDBC GCS supports wild char upload.
> `put file:///home/test/test_file*.csv`
> uploads files matching the pattern in parallel. Does the current implementation support this?

There was a thread safe issue on odbc side and I just committed the fix. It should work now.
Sorry I was testing with one large file and one small file so it was not really in parallel.

**Comment by SimbaGithub** [comment]
> @SimbaGithub Add a test case for GCS put/get and verify file. A reference implementation is available in test_simple_put.cpp

GCS put/get is not available for libsnowflakeclient, it can only be used for ODBC driver. GCS put/get is using http for the put/get request and ODBC is using it's own implementation of http request. I think this change is for ODBC May release so I only add http put/get implementation in ODBC. For now in libsnowflakeclient GCS put/get will fail.

**Comment by sfc-gh-stakeda** [comment]
@SimbaGithub , interesting. I was not aware it is possible to implement PUT and GET command without libsnowflakeclient. @rvishureddy can you please confirm? We want to enable PUT and GET tests for libsnowflakeclient anywa.

**Comment by sfc-gh-stakeda** [comment]
@rvishureddy can we merge this?

**Comment by rvishureddy** [comment]
@smtakeda Yes it is possible as for GCS we are using REST API. 
And for AWS and Azure we are using SDK's and we moved those to libsnowflakeclient. 
Enabling put/get tests for Azure/Aws in libsnowflakeclient. 

Given this do we plan to have GCP put/get support in both ODBC and libsnowflakeclient (Two different implementations)?

**Comment by sfc-gh-stakeda** [comment]
@SimbaGithub , we'll merge this PR for now towards the next ODBC release, but please move PUT and GET for GCP implementation to libsnowflakeclient to make consistent with AWS and Azure. I'll file a ticket.

**Comment by SimbaGithub** [comment]
> @SimbaGithub , we'll merge this PR for now towards the next ODBC release, but please move PUT and GET for GCP implementation to libsnowflakeclient to make consistent with AWS and Azure. I'll file a ticket.

Sure. That can be after the May release of ODBC, right?

**Comment by sfc-gh-stakeda** [comment]
@SimbaGithub yes, that's right. Let's do after the upcoming release.

Also @rvishureddy will move the ARROW library from `ODBC` to `libsnowflakeclient` as well such that all dependencies will be built and maintained here for other drivers to consume, e.g., PHP.

**Pull request merged**
