### PR TITLE
Upgrade dependencies for security vulnerabilities

### PR DESCRIPTION
**Pull request by SimbaGithub**
upgrade openssl to 1.1.1g
upgrade util-linux to 2.36

### CODE REVIEW

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-vreddy , FYI.

**Review by sfc-gh-stakeda — APPROVED** [review]
LGTM.
@sfc-gh-vreddy , after this change is merged, we'll need to have a release tag.

**Review by sfc-gh-vreddy — APPROVED** [review]
Openssl 1.1.1h is released, but does not have any security fixes. 
openssl 1.1.1g is good enough.

**Comment by sfc-gh-vreddy** [comment]
@sfc-gh-sshankar This PR fixes upgrades Openssl and util-linux third party packages.

**Pull request merged**
