### PR TITLE
Enable put/get tests on AWS and AZURE

### PR DESCRIPTION
**Pull request by rvishureddy**
Currently enabled put get tests on AWS and AZURE

### CODE REVIEW

**Comment by sfc-gh-stakeda** [comment]
@rvishureddy can we merge this today?
We need to bump up the version and have the ODBC pick up the changes.

**Comment by rvishureddy** [comment]
> @rvishureddy can we merge this today?
> We need to bump up the version and have the ODBC pick up the changes.

Yes it should be done.

**Comment by sfc-gh-stakeda** [comment]
Sorry, this has been pending long time. Can you please ensure all test pass?

**Comment by rvishureddy** [comment]
@sfc-gh-stakeda  Windows test fails because of following error. Are there any simultaneous tests running?

>  C:\Users\RUNNER~1\AppData\Local\Temp\\snowflakeTmp\521a3ea6-40ae-4148-9e8f-3a81a0ee1eb7\small_file.csv.gz - The process cannot access the file because it is being used by another process.

**Comment by SimbaGithub** [comment]
> @sfc-gh-stakeda Windows test fails because of following error. Are there any simultaneous tests running?
> 
> > C:\Users\RUNNER~1\AppData\Local\Temp\snowflakeTmp\521a3ea6-40ae-4148-9e8f-3a81a0ee1eb7\small_file.csv.gz - The process cannot access the file because it is being used by another process.

Hi @rvishureddy ,
I think it's failed on test_simple_get and not related to the file being used. There is a special character '~' in temp path and caused the query fail. Exception was thrown when query failed so the test case stop there and no message out.
I had a fix for that in my PR here, make the path quoted in the query and it will pass.
https://github.com/snowflakedb/libsnowflakeclient/pull/203/commits/b7cb1e41808878ab7e4e14d34f3cc7a330c2e560

Thanks,
Harry

**Comment by sfc-gh-stakeda** [comment]
@rvishureddy Do we still need this PR?

**Pull request closed without merging**
