### PR TITLE
SNOW 345673 Rotated secrets

### PR DESCRIPTION
**Pull request by sfc-gh-hchaturvedi**
Rotated Secrets

### CODE REVIEW

**Review by sfc-gh-kwagner — APPROVED** [review]
LGTM

**Comment by sfc-gh-kwagner** [comment]
@sfc-gh-hchaturvedi looks like the user is locked. Can you reset the password for the user in the proper accounts and restart the tests?

**Comment by sfc-gh-hchaturvedi** [comment]
> @sfc-gh-hchaturvedi looks like the user is locked. Can you reset the password for the user in the proper accounts and restart the tests?

Resetting the password is going to be a very painful exercise. Let me try unlocking the user

**Comment by sfc-gh-mkeller** [comment]
I think we should be okay to merge this without the tests completing.
It won't get worse than this 😅
But seriously none of the tests fail because of wrong password.
Maybe we could find the reason for the Locking up on Jenkins after

**Pull request merged**
