### PR TITLE
mask logging of sensitive information from AWS SDK

### PR DESCRIPTION
**Pull request by SimbaGithub**
This change can fix the test case failure for logging of put/get on GCP.

### CODE REVIEW

**Comment by sfc-gh-stakeda** [comment]
Hold on this change. I'm patching the ODBC test failure.

**Comment by sfc-gh-stakeda** [comment]
@h-chaturvedi and @rvishureddy , can you check if these mask are reasonable?

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-wshangguan do we still want to have this fix for ODBC? If not, can we close this?

**Comment by sfc-gh-wshangguan** [comment]
@sfc-gh-stakeda I think we still need this for AWS logger because we don't have secret detector in libsnowflakeclient. And SFAwsLogger is isolated from external logger which will be passed in. In other words, SecretDetector in ODBC can't help with masking sensitive data generated by AWS SDK.

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-wshangguan , ok, thanks for quick look. I'll leave this PR to you anyway.

**Comment by sfc-gh-wshangguan** [comment]
@sfc-gh-stakeda Oh, you mean we need to merge the pr ourselves instead of just approve it? And btw, is there any related JIRA for more background information?

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-wshangguan , I mean I leave this to your to decided 1) approve and merge this change 2) you write your wrapper to include this. This PR was raised initially to pass an ad-hoc security tests. Now you are working on the similar framework across all drivers, I'll let you decide how to treat this change.

**Comment by sfc-gh-wshangguan** [comment]
https://snowflakecomputing.atlassian.net/browse/SNOW-170938

**Pull request merged**
