### PR TITLE
[#87] SNOW-715854: SNOW-665303: Add source code for all dependencies for Snyk test

### PR DESCRIPTION
**Pull request by sfc-gh-ext-simba-jl**
Request: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/87
Snyk requirements for C++: https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-c-c++

The source code for all dependencies have been added in the deps folder to satisfy Snyk's requirements.
Snyk test result: [snyk_libsnowflakeclient_PR492.txt](https://github.com/snowflakedb/libsnowflakeclient/files/10549368/snyk_libsnowflakeclient_PR492.txt)

Build dependencies of libsnowflakeclient:

- arrow-0.17.1 (cloned from github): 8189792b7b36f3b9f9d6d2de5efd1aa256432e12
- aws-sdk-cpp-1.3.50
- azure-storage-cpplite-0.1.20 (cloned from github): ed28bc7951c5d711df5093fc94ada595f054630f
- boost-1.75.0 (extracted from boost-1.75.0.zip): 393a0071dca07e50249502cb4c3a323f8013d644
- cmocka-1.1.1
- curl-7.87.0
- oob-1.0.4 (not an open source dependency)
- openssl-1.1.1q (extracted from openssl-1.1.1q.zip): 22c5cf6a49d976a45bd13ba6b18bcb94ad251363
- util-linux-2.36.1 (aka uuid, extracted from util-linux.tar.gz): 1679d67ba327ab01d614a5e2f1c0d4190bb887e6
- zlib-1.2.11.1

Build scripts are updated to reflect the new folder name and added a link to the GitHub repo for future reference: ee2ae3d02b30d9c00a127e68e6bb3f72a19a194a

Changes to some file permissions in order to build on Linux: cd9d25f4ef17ff62671c4b5775c79b2b1f6deeda

### CODE REVIEW

**Review by sfc-gh-igarish — APPROVED** [review]
Looks like too many files added, as I can't see file list. If you see all tests pass then merge it. If you have file list changed/added, please put in the comment. github is not able to show any files.

**Comment by sfc-gh-igarish** [comment]
@sfc-gh-ext-simba-jl could you please add label. is this for ODBC or libsfclient?

**Comment by sfc-gh-jfan** [comment]
Hello, @sfc-gh-ext-simba-jl, I wanna raise this topic again with Simba team on our software composition analysis requirements on C++ scanning. 

could you please let me know if you can meet the requirements listed below?
1. List down all C++ direct and transitive(if there is any) open source dependencies which are used in snowflake-odbc repository
2. Provide C++ source code of open source dependencies listed in #1 and push to snowflake-odbc repository Dependencies folder because source code is a requirement for Snyk to do the scanning on C++

if Simba cannot do that, is Simba able to provide a dependency scanning report instead for our compliance requirements?

please let me know your thoughts on above, thanks!

**Comment by sfc-gh-ext-simba-jl** [comment]
@sfc-gh-igarish I've separated into multiple commits and no source code is changed. They are either extracted from zip/tar.gz or cloned from the open source repo. We are in code freeze since last week so I'll merge the PR after the release is done.

@sfc-gh-jfan I'll move the snowflake-odbc discussion to the internal issue https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/87 Please check the comments there.

**Comment by sfc-gh-igarish** [comment]
LGTM. thx

**Comment by sfc-gh-ext-simba-jl** [comment]
@sfc-gh-igarish Can you approve the PR again? The merging seems to be blocked: "The base branch does not allow updates."

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by sfc-gh-igarish** [comment]
@sfc-gh-ext-simba-jl Kiran locked the branch for a release. Please check with him.

**Pull request merged**
