### PR TITLE
Add SecretDetector to mask secret information in log

### PR DESCRIPTION
**Pull request by SimbaGithub**
Simba incident: 00279252

### CODE REVIEW

**Comment by sfc-gh-hchaturvedi** [comment]
Hey @SimbaGithub have we done any manual testing looking at logs ensuring this is working? I had put some examples of current leaks in the case comments. Can we run this and ensure they're mitigated now?

**Comment by sfc-gh-hchaturvedi** [comment]
Hey @SimbaGithub have we done any manual testing looking at logs ensuring this is working? I had put some examples of current leaks in the case comments. Can we run this and ensure they're mitigated now?

**Comment by sfc-gh-hchaturvedi** [comment]
> Hey @SimbaGithub have we done any manual testing looking at logs ensuring this is working? I had put some examples of current leaks in the case comments. Can we run this and ensure they're mitigated now?

@SimbaGithub any comments on this ^^

**Comment by SimbaGithub** [comment]
> > Hey @SimbaGithub have we done any manual testing looking at logs ensuring this is working? I had put some examples of current leaks in the case comments. Can we run this and ensure they're mitigated now?
> 
> @SimbaGithub any comments on this ^^

I've done manual testing and confirmed leaks mentioned in the case comments are masked. Also the added test cases in test_unit_logger should cover all those leaks in all logs in libsnowflakeclient.
Please hold on this PR though. I've found performance issue of std:regex. With current implementation logging is 10 times slower. Replace std::regex with boost::regex can solve the issue.
@sfc-gh-vreddy Since we already have boost libs in arrow, could you add header files of boost so we can use boost::regex?

**Comment by sfc-gh-vreddy** [comment]
@sfc-gh-hchaturvedi Provided harry with boost headers, @SimbaGithub will come up with perf results between std::regex vs boost.

**Comment by SimbaGithub** [comment]
> @sfc-gh-hchaturvedi Provided harry with boost headers, @SimbaGithub will come up with perf results between std::regex vs boost.

I've tested on Windows and Linux and confirmed that boost::regex is 20+ times faster than std::regex.
@sfc-gh-vreddy could you make boost libraries separated from arrow? Different from arrow, we need boost on Win 32-bit as well.

**Review by sfc-gh-vreddy — APPROVED** [review]
LGTM

**Pull request merged**
